---
Parameters:
  KeyName:
    Description: KeyPair to use for SSH Access
    Type: String
    Default: primary
  OS:
    Description: VM OS ( ubuntu-20 / amazon-linux-2 / rhel-8 ) specific to the stack AZ ap-south-1
    Type: String
    Default: ubuntu-20

Mappings:
  OSMap:
    ubuntu-20:
      AMI: ami-0c1a7f89451184c8b
    amazon-linux-2:
      AMI: ami-04db49c0fb2215364
    rhel-8:
      AMI: ami-04db49c0fb2215364

Resources:
  publicInstance:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: !FindInMap
        - OSMap
        - !Ref OS
        - AMI
      InstanceType: t2.micro
      KeyName: !Ref KeyName
      SecurityGroupIds:
        - !GetAtt publicInstanceSG.GroupId
      AvailabilityZone: ap-south-1b
      Tags:
        - Key: Name
          Value: Test-Public-EC2-Instance

  publicInstanceSG:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Default Access Security Group 
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: '22' 
          ToPort: '22'
          CidrIp: '0.0.0.0/0'
      Tags:
        - Key: Name
          Value: Instance Security Group

Outputs:
  instanceIpv4:
    Value: !GetAtt publicInstance.PublicDnsName
  instanceVpcIpv4:
    Value: !GetAtt publicInstance.PrivateDnsName