---
- hosts: openvpn_server
  gather_facts: yes
  become: yes
  
  vars_files: 
    - vars.yml

  tasks:
    - name: Install OpenVPN
      apt:
        name: openvpn
        state: present
        update_cache: yes
      notify: restart openvpn
    
    - name: Install UFW
      apt:
        name: ufw
        state: present

    - name: Copy over Server Configuration File
      copy:
        src: "{{ server_conf_file }}"
        dest: /etc/openvpn/server.conf
        mode: '0644'
      notify: restart openvpn

    - name: Ensuring Client Config Dir exists
      file:
        path: /etc/openvpn/ccd
        state: directory

    - name: Copy over Server Certificate File
      copy:
        src: "{{ server_cert_file }}"
        dest: /etc/openvpn/server.crt
        mode: '0644'
      notify: restart openvpn

    - name: Copy over Server Private Key
      copy:
        src: "{{ server_private_key }}"
        dest: /etc/openvpn/server.key
        mode: '0400'
      notify: restart openvpn
    
    - name: Copy over CA Certificate
      copy:
        src: "{{ ca_certificate_file }}"
        dest: /etc/openvpn/ca.crt
        mode: '0644'
      notify: restart openvpn

    - name: Copy over DH Key
      copy:
        src: "{{ dh_key_file }}"
        dest: /etc/openvpn/dh.pem
        mode: '0400'
      notify: restart openvpn

    - name: Copy over TA Key
      copy:
        src: "{{ ta_key_file }}"
        dest: /etc/openvpn/ta.key
        mode: '0400'
      notify: restart openvpn
    
    - name: Enable IP Forwarding
      sysctl:
        name: net.ipv4.ip_forward
        value: '1'
        sysctl_set: yes
      notify: restart openvpn

    - name: Update UFW before.rules
      template:
        src: etc_ufw_before.rules.j2
        dest: /etc/ufw/before.rules
        owner: root
        group: root
        mode: '0640'
      notify: restart openvpn
    
    - name: Update UFW default rules
      template:
        src: etc_default_ufw.j2
        dest: /etc/default/ufw
        owner: root
        group: root
        mode: '0644'
      notify: restart openvpn
    
    - name: Allow everything and enable UFW
      ufw:
        state: enabled
        policy: allow

    - name: Enable OpenVPN Server
      service:
        name: 'openvpn@server'
        enabled: yes

  handlers:
    - name: restart openvpn
      service:
        name: 'openvpn@server'
        state: restarted