---
- hosts: all
  gather_facts: no
  become: yes

  tasks:
    - name: Install OpenVPN
      apt:
        name: openvpn
        state: present
        update_cache: yes
      notify: restart openvpn
    
    - name: Copy over Client Configuration File
      copy:
        src: "clients/{{ client_name }}/{{ client_name }}.ovpn"
        dest: /etc/openvpn/client.conf
        owner: root
        group: root
        mode: '0400'
      notify: restart openvpn

    - name: Enable OpenVPN Server
      service:
        name: 'openvpn@client'
        enabled: yes

  handlers:
    - name: restart openvpn
      service:
        name: 'openvpn@client'
        state: restarted