---
- hosts: raspberrypi
  gather_facts: no
  become: yes
  
  vars: 
    workdir: /home/git/gitea
    package_url: https://dl.gitea.io/gitea/1.15.2/gitea-1.15.2-linux-arm-5

  tasks:
    - name: ensure git is installed
      apt:
        name: git
        state: present
        update_cache: yes
      notify: restart gitea
    
    - name: ensuring user 'git' exists
      user:
        name: git
        comment: git user for gitea
        uid: 1010
        shell: /bin/bash
    
    - name: ensuring gitea directory exists
      file:
        path: /home/git/gitea
        state: directory
    
    - name: ensuring UFW is installed
      apt:
        name: ufw
        state: present
    
    - name: ensuring UFW allows ssh connections
      community.general.ufw:
        rule: allow
        name: OpenSSH

    - name: ensuring UFW allows connections on port 3000 and is enabled
      community.general.ufw:
        rule: allow
        port: 3000
        state: enabled
      
    - name: ensuring service configuration file exists
      template:
        src: templates/gitea.service.j2
        dest: /etc/systemd/system/gitea.service
        mode: '0644'
      notify: restart gitea

    - name: ensuring gitea binary is present
      get_url:
        url: '{{ package_url }}'
        dest: /home/git/gitea/gitea
        mode: '0544'
        owner: git
      notify: restart gitea
    
    - name: ensuring gitea service is enabled
      service:
        name: 'gitea'
        enabled: yes

  handlers:
    - name: restart gitea
      service:
        name: 'gitea'
        state: restarted